### ISSUE TITLE
Cannot make simulations using the tree algorithm

### ISSUE THREAD

**Issue by sshann** [praalhans/DaViz#2]
### Description

When trying to run simulations with the tree algorithm, an error message `The network contains cycles` is displayed when no cycles are present.

### Steps to reproduce

1.  Create any network without cycles
2. Select the tree algorithm
3. Start simulation
4. The error is displayed and the simulation is not executed

### Cause

The checker that verifies if there are cycles in the network is not implemented.

### Steps to solve
- [x] Implement the acyclic checker.

**Comment by sshann** [comment]
After implementing the acyclic checker, the application fails at

```Java
Worker thread job failed with exception
java.lang.NullPointerException
	at com.aexiz.daviz.Controller.lambda$2(Controller.java:490)
	at com.aexiz.daviz.SimulationManager.lambda$11(SimulationManager.java:808)
	at com.aexiz.daviz.SimulationManager$2.run(SimulationManager.java:833)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sshann** [comment]
Upon further inspection, the Exception is caused by attempting to start in the initiator selected by the user. Given the tree algorithm is not centralized, no initiator needs to be selected. For these cases, a random node can be selected as initiator

**Comment by sshann** [comment]
> Upon further inspection, the Exception is caused by attempting to start in the initiator selected by the user. Given the tree algorithm is not centralized, no initiator needs to be selected. For these cases, a random node can be selected as the initiator of the computation.

Correction, the simulation already takes care of decentralized computation, no need to set an initiator in the stage of the exception. Furthermore, the exception takes place when the application attempts to verify if the selected initiators exist in the topology. Therefore, this checker only needs to run if an initiator is in fact selected by the user

**Comment by sshann** [comment]
The initiator input is not erased when setting the field to disabled, which cause the application to fail if an initiator was previously selected before running the tree algorithm:
```
Exception in thread "Thread-0" java.lang.Error: Algorithm is not centralized by user-input
	at com.aexiz.daviz.glue.Simulation.setInitiator(Simulation.java:49)
	at com.aexiz.daviz.Controller.lambda$2(Controller.java:521)
	at com.aexiz.daviz.SimulationManager.lambda$11(SimulationManager.java:808)
	at com.aexiz.daviz.SimulationManager$2.run(SimulationManager.java:833)
	at java.lang.Thread.run(Thread.java:748)
```
